import { describe, expect, it } from 'vitest';
import type { Transaction } from '../types';
import { migrateLegacySettlement } from './migrations';

function legacyTransaction(overrides: Partial<Transaction> = {}): Transaction {
  return {
    id: 'legacy-settlement',
    description: '🤝 Settle: Alice paid You',
    amount: 75,
    currency: 'HKD',
    rate: 1,
    date: '2026-08-13',
    category: 'Others',
    type: 'expense',
    paidBy: 'alice',
    isPersonal: false,
    splitMode: 'custom',
    splits: [{ participantId: 'me', amount: 75 }],
    ...overrides,
  };
}

describe('legacy settlement migration', () => {
  it('converts records generated by the old Paid & Settle action', () => {
    expect(migrateLegacySettlement(legacyTransaction())).toMatchObject({
      type: 'settlement',
      settlementFrom: 'alice',
      settlementTo: 'me',
    });
  });

  it('does not convert an ordinary custom group expense', () => {
    const transaction = legacyTransaction({ description: 'Shared supplies' });
    expect(migrateLegacySettlement(transaction)).toBe(transaction);
  });
});
