import type { AppState, Transaction } from '../types';

const LEGACY_SETTLEMENT_PREFIX = '🤝 Settle:';

/**
 * Older SplitTrack versions recorded settlement payments as custom group
 * expenses. Convert only the exact shape generated by the old Paid & Settle
 * action so ordinary user-created expenses are left untouched.
 */
export function migrateLegacySettlement(transaction: Transaction): Transaction {
  const recipient = transaction.splits[0];
  const isGeneratedLegacySettlement =
    transaction.type === 'expense' &&
    !transaction.isPersonal &&
    transaction.category === 'Others' &&
    transaction.splitMode === 'custom' &&
    transaction.description.startsWith(LEGACY_SETTLEMENT_PREFIX) &&
    transaction.splits.length === 1 &&
    Math.abs(recipient.amount - transaction.amount) < 0.01;

  if (!isGeneratedLegacySettlement) return transaction;

  return {
    ...transaction,
    type: 'settlement',
    settlementFrom: transaction.paidBy,
    settlementTo: recipient.participantId,
  };
}

export function migrateAppState(state: AppState): AppState {
  return {
    ...state,
    transactions: state.transactions.map(migrateLegacySettlement),
  };
}
